### ISSUE TITLE
Failing build on PostgreSQL Version 15.1 

### ISSUE THREAD

**Issue by sabman** [duckdb/pg_duckdb#148]
We just tried to build on PostgreSQL Version 15.1

build Dockerfile snippet:

```dockerfile
# main commit hash as at 2024-08-22:21:12:07 
ARG pg_duckdb_release=f0d41bad5988db2c71ebe3d038bbb93f2208d3c5  
RUN git clone https://github.com/duckdb/pg_duckdb.git /tmp/pg_duckdb
WORKDIR /tmp/pg_duckdb
RUN git checkout ${pg_duckdb_release}
RUN make install
```

```
#189 1688.9 src/scan/postgres_scan.cpp:60:102: error: too many arguments to function ‘List* stringToQualifiedNameList(const char*)’
```

As there still isn't a release would you recommend trying a different branch or different commit hash?

**Comment by wuputah** [comment]
This is expected at the moment; Postgres 15 is not currently supported. Please use Postgres 16 or 17 for now.

Closing in favor of consolidating in #145 for Postgres 15 support.
